config/routes.rb
Rails.application.routes.draw do
  resources :guest_houses

  root 'guest_houses#index'

end

app/models/guest_house.rb
class GuestHouse < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guest_houses_controller.rb
class GuestHousesController < ApplicationController
  before_action :set_guest_house, only: [:show, :edit, :update, :destroy]

  # GET /guest_houses
  # GET /guest_houses.json
  def index
    @guest_houses = GuestHouse.all
  end

  # GET /guest_houses/1
  # GET /guest_houses/1.json
  def show
  end

  # GET /guest_houses/new
  def new
    @guest_house = GuestHouse.new
  end

  # GET /guest_houses/1/edit
  def edit
  end

  # POST /guest_houses
  # POST /guest_houses.json
  def create
    @guest_house = GuestHouse.new(guest_house_params)

    respond_to do |format|
      if @guest_house.save
        format.html { redirect_to @guest_house, notice: 'Guest house was successfully created.' }
        format.json { render :show, status: :created, location: @guest_house }
      else
        format.html { render :new }
        format.json { render json: @guest_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guest_houses/1
  # PATCH/PUT /guest_houses/1.json
  def update
    respond_to do |format|
      if @guest_house.update(guest_house_params)
        format.html { redirect_to @guest_house, notice: 'Guest house was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest_house }
      else
        format.html { render :edit }
        format.json { render json: @guest_house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guest_houses/1
  # DELETE /guest_houses/1.json
  def destroy
    @guest_house.destroy
    respond_to do |format|
      format.html { redirect_to guest_houses_url, notice: 'Guest house was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest_house
      @guest_house = GuestHouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_house_params
      params.require(:guest_house).permit(:name, :city_id, :stars_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_houses_helper.rb
module GuestHousesHelper
end

app/views/guest_houses/_form.html.erb
<%= form_for(@guest_house) do |f| %>
  <% if @guest_house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest_house.errors.count, "error") %> prohibited this guest_house from being saved:</h2>

      <ul>
      <% @guest_house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.number_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :stars_count %><br>
    <%= f.number_field :stars_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guest_houses/edit.html.erb
<h1>Editing guest_house</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest_house %> |
<%= link_to 'Back', guest_houses_path %>

app/views/guest_houses/index.html.erb
<h1>Listing guest_houses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Stars count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guest_houses.each do |guest_house| %>
      <tr>
        <td><%= guest_house.name %></td>
        <td><%= guest_house.city_id %></td>
        <td><%= guest_house.stars_count %></td>
        <td><%= link_to 'Show', guest_house %></td>
        <td><%= link_to 'Edit', edit_guest_house_path(guest_house) %></td>
        <td><%= link_to 'Destroy', guest_house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest house', new_guest_house_path %>

app/views/guest_houses/new.html.erb
<h1>New guest_house</h1>

<%= render 'form' %>

<%= link_to 'Back', guest_houses_path %>

app/views/guest_houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest_house.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @guest_house.city_id %>
</p>

<p>
  <strong>Stars count:</strong>
  <%= @guest_house.stars_count %>
</p>

<%= link_to 'Edit', edit_guest_house_path(@guest_house) %> |
<%= link_to 'Back', guest_houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hotel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>